SELECT MCDP_CD AS '진료과 코드', COUNT(DISTINCT PT_NO) AS '5월예약건수'
# SELECT *
FROM APPOINTMENT
WHERE YEAR(APNT_YMD) = 2022 AND MONTH(APNT_YMD) = 5
GROUP BY MCDP_CD
ORDER BY COUNT(DISTINCT PT_NO) ASC, MCDP_CD ASC;