SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO AS I
JOIN FISH_NAME_INFO AS N
ON I.FISH_TYPE = N.FISH_TYPE
WHERE I.LENGTH = (
    SELECT MAX(A.LENGTH)
    FROM FISH_INFO AS A
    WHERE I.FISH_TYPE = A.FISH_TYPE)
ORDER BY I.ID
;